version: "3"
services:
  mtg1test:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: mtg1test
    environment:
      - node.name=mtg1test
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - /Users/bojilovv/Projects/graphql-montage/data/:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    depends_on:
      - mtg1test
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
